server:
  port: 80
manager:
  version: "1.0"
  udp:
    port: 20001
    timeout: 81000
  token:
    expiry: 900000
    expiredRemovalPeriod: 60000
    secret: oVZb0eZtmGaDiUmVrqfO98Duek7ZTpjD
  refreshToken:
    expiry: 3600000
  admin:
    password: $2y$10$fTWtWIiJ44bY/ZoPi1lWm.9cgm//k6i/9ZjzFzAFUKhuA9BGd7S4u
  user:
    password: $2y$10$Yfife..KkelrQqz5UpdnIeG56bboCAg1fdoUqrPJQrOnC.1uv.spa
controller:
  configFile: "/opt/homeheat/conf/HomeHeat.yml"

