
extMinTemp: -18.0
extMaxTemp: 12.0
extStartThreshold: 0.15
tempBaseLevel: 20.0
nightStartTime: 22:01:00
nightEndTime: 6:59:00
dayStartTime: 13:01:00
dayEndTime: 15:59:00
logLevel: INFO

circuits:
  - index: 0
    description: kitchen
    active: false
    maxTemp: 35.0
    tempBaseLevel: 20.0
    heatCharacteristics:
      - tempMax: 20.0
        heatFactor: 8.3333e-4
      - tempMax: 23.0
        heatFactor: 8.3333e-4
      - tempMax: 26.0
        heatFactor: 8.3333e-4
      - tempMax: 30.0
        heatFactor: 8.3333e-4
      - tempMax: 100.0
        heatFactor: 8.3333e-4
  - index: 1
    description: living room
    active: false
    maxTemp: 30.0
    tempBaseLevel: 20.0
    heatCharacteristics:
      - tempMax: 20.0
        heatFactor: 8.3333e-4
      - tempMax: 23.0
        heatFactor: 8.3333e-4
      - tempMax: 26.0
        heatFactor: 8.3333e-4
      - tempMax: 30.0
        heatFactor: 8.3333e-4
      - tempMax: 100.0
        heatFactor: 8.3333e-4
  - index: 2
    description: boys' room 1
    active: false
    maxTemp: 30.0
    tempBaseLevel: 20.0
    heatCharacteristics:
      - tempMax: 20.0
        heatFactor: 8.3333e-4
      - tempMax: 23.0
        heatFactor: 8.3333e-4
      - tempMax: 26.0
        heatFactor: 8.3333e-4
      - tempMax: 30.0
        heatFactor: 8.3333e-4
      - tempMax: 100.0
        heatFactor: 8.3333e-4
  - index: 3
    description: boys' room 2
    active: false
    maxTemp: 30.0
    tempBaseLevel: 20.0
    heatCharacteristics:
      - tempMax: 20.0
        heatFactor: 8.3333e-4
      - tempMax: 23.0
        heatFactor: 8.3333e-4
      - tempMax: 26.0
        heatFactor: 8.3333e-4
      - tempMax: 30.0
        heatFactor: 8.3333e-4
      - tempMax: 100.0
        heatFactor: 8.3333e-4
  - index: 4
    description: hall
    active: false
    maxTemp: 30.0
    tempBaseLevel: 20.0
    heatCharacteristics:
      - tempMax: 20.0
        heatFactor: 8.3333e-4
      - tempMax: 23.0
        heatFactor: 8.3333e-4
      - tempMax: 26.0
        heatFactor: 8.3333e-4
      - tempMax: 30.0
        heatFactor: 8.3333e-4
      - tempMax: 100.0
        heatFactor: 8.3333e-4
  - index: 5
    description: office room
    active: false
    maxTemp: 30.0
    tempBaseLevel: 20.0
    heatCharacteristics:
      - tempMax: 20.0
        heatFactor: 8.3333e-4
      - tempMax: 23.0
        heatFactor: 8.3333e-4
      - tempMax: 26.0
        heatFactor: 8.3333e-4
      - tempMax: 30.0
        heatFactor: 8.3333e-4
      - tempMax: 100.0
        heatFactor: 8.3333e-4
  - index: 6
    description: our bedroom
    active: false
    maxTemp: 30.0
    tempBaseLevel: 20.0
    heatCharacteristics:
      - tempMax: 20.0
        heatFactor: 8.3333e-4
      - tempMax: 23.0
        heatFactor: 8.3333e-4
      - tempMax: 26.0
        heatFactor: 8.3333e-4
      - tempMax: 30.0
        heatFactor: 8.3333e-4
      - tempMax: 100.0
        heatFactor: 8.3333e-4
  - index: 7
    description: our bathroom
    active: false
    maxTemp: 40.0
    tempBaseLevel: 20.0
    heatCharacteristics:
      - tempMax: 20.0
        heatFactor: 8.3333e-4
      - tempMax: 23.0
        heatFactor: 8.3333e-4
      - tempMax: 26.0
        heatFactor: 8.3333e-4
      - tempMax: 30.0
        heatFactor: 8.3333e-4
      - tempMax: 100.0
        heatFactor: 8.3333e-4
  - index: 8
    description: bathroom
    active: false
    maxTemp: 40.0
    tempBaseLevel: 20.0
    heatCharacteristics:
      - tempMax: 20.0
        heatFactor: 8.3333e-4
      - tempMax: 23.0
        heatFactor: 8.3333e-4
      - tempMax: 26.0
        heatFactor: 8.3333e-4
      - tempMax: 30.0
        heatFactor: 8.3333e-4
      - tempMax: 100.0
        heatFactor: 8.3333e-4
  - index: 9
    description: technical room
    active: false
    maxTemp: 35.0
    tempBaseLevel: 20.0
    heatCharacteristics:
      - tempMax: 20.0
        heatFactor: 8.3333e-4
      - tempMax: 23.0
        heatFactor: 8.3333e-4
      - tempMax: 26.0
        heatFactor: 8.3333e-4
      - tempMax: 30.0
        heatFactor: 8.3333e-4
      - tempMax: 100.0
        heatFactor: 8.3333e-4
