
extMinTemp: -18.0
extMaxTemp: 12.0
extStartThreshold: 0.15
tempBaseLevel: 20.0
nightStartTime: 22:00:00
nightEndTime: 6:58:00
dayStartTime: 13:00:00
dayEndTime: 15:58:00
logLevel: DEBUG

circuits:
  - index: 0
    description: kitchen
    active: true
    maxTemp: 35.0
    tempBaseLevel: 20.0
    heatCharacteristics:
      - tempMax: 20.0
        heatFactor: 1.0384e-3
      - tempMax: 23.0
        heatFactor: 1.0384e-3
      - tempMax: 26.0
        heatFactor: 1.0384e-3
      - tempMax: 30.0
        heatFactor: 1.0384e-3
      - tempMax: 100.0
        heatFactor: 1.0384e-3
  - index: 1
    description: living room
    active: true
    maxTemp: 30.0
    tempBaseLevel: 20.0
    heatCharacteristics:
      - tempMax: 20.0
        heatFactor: 7.1031e-4
      - tempMax: 23.0
        heatFactor: 7.1031e-4
      - tempMax: 26.0
        heatFactor: 7.1031e-4
      - tempMax: 30.0
        heatFactor: 7.1031e-4
      - tempMax: 100.0
        heatFactor: 7.1031e-4
  - index: 2
    description: boys' room 1
    active: true
    maxTemp: 30.0
    tempBaseLevel: 20.0
    heatCharacteristics:
      - tempMax: 20.0
        heatFactor: 8.3333e-4
      - tempMax: 23.0
        heatFactor: 8.3333e-4
      - tempMax: 26.0
        heatFactor: 8.3333e-4
      - tempMax: 30.0
        heatFactor: 8.3333e-4
      - tempMax: 100.0
        heatFactor: 8.3333e-4
  - index: 3
    description: boys' room 2
    active: true
    maxTemp: 30.0
    tempBaseLevel: 20.0
    heatCharacteristics:
      - tempMax: 20.0
        heatFactor: 8.3333e-4
      - tempMax: 23.0
        heatFactor: 8.3333e-4
      - tempMax: 26.0
        heatFactor: 8.3333e-4
      - tempMax: 30.0
        heatFactor: 8.3333e-4
      - tempMax: 100.0
        heatFactor: 8.3333e-4
  - index: 4
    description: hall
    active: true
    maxTemp: 30.0
    tempBaseLevel: 20.0
    heatCharacteristics:
      - tempMax: 20.0
        heatFactor: 8.3333e-4
      - tempMax: 23.0
        heatFactor: 8.3333e-4
      - tempMax: 26.0
        heatFactor: 8.3333e-4
      - tempMax: 30.0
        heatFactor: 8.3333e-4
      - tempMax: 100.0
        heatFactor: 8.3333e-4
  - index: 5
    description: office room
    active: true
    maxTemp: 30.0
    tempBaseLevel: 20.0
    heatCharacteristics:
      - tempMax: 20.0
        heatFactor: 6.5e-4
      - tempMax: 23.0
        heatFactor: 6.5e-4
      - tempMax: 26.0
        heatFactor: 6.5e-4
      - tempMax: 30.0
        heatFactor: 6.5e-4
      - tempMax: 100.0
        heatFactor: 6.5e-4
  - index: 6
    description: our bedroom
    active: true
    maxTemp: 30.0
    tempBaseLevel: 20.0
    heatCharacteristics:
      - tempMax: 20.0
        heatFactor: 8.3333e-4
      - tempMax: 23.0
        heatFactor: 8.3333e-4
      - tempMax: 26.0
        heatFactor: 8.3333e-4
      - tempMax: 30.0
        heatFactor: 8.3333e-4
      - tempMax: 100.0
        heatFactor: 8.3333e-4
  - index: 7
    description: our bathroom
    active: true
    maxTemp: 40.0
    tempBaseLevel: 20.0
    heatCharacteristics:
      - tempMax: 20.0
        heatFactor: 9.0074e-4
      - tempMax: 23.0
        heatFactor: 9.0074e-4
      - tempMax: 26.0
        heatFactor: 9.0074e-4
      - tempMax: 30.0
        heatFactor: 9.0074e-4
      - tempMax: 100.0
        heatFactor: 9.0074e-4
  - index: 8
    description: bathroom
    active: true
    maxTemp: 40.0
    tempBaseLevel: 20.0
    heatCharacteristics:
      - tempMax: 20.0
        heatFactor: 1.0102e-3
      - tempMax: 23.0
        heatFactor: 1.0102e-3
      - tempMax: 26.0
        heatFactor: 1.0102e-3
      - tempMax: 30.0
        heatFactor: 1.0102e-3
      - tempMax: 100.0
        heatFactor: 1.0102e-3
  - index: 9
    description: technical room
    active: true
    maxTemp: 35.0
    tempBaseLevel: 20.0
    heatCharacteristics:
      - tempMax: 20.0
        heatFactor: 8.3333e-4
      - tempMax: 23.0
        heatFactor: 8.3333e-4
      - tempMax: 26.0
        heatFactor: 8.3333e-4
      - tempMax: 30.0
        heatFactor: 8.3333e-4
      - tempMax: 100.0
        heatFactor: 8.3333e-4
